function T = computeT(xstar, Lcstar, Ltstar, T1, T2)
T = (xstar > Lcstar).*T2 + (xstar < Lcstar-Ltstar).*T1 +...
        ((xstar <= Lcstar) & (xstar >= (Lcstar-Ltstar))).*...
        ((xstar - Lcstar + Ltstar).*(T2 - T1)./Ltstar + T1);